apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-ease-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-ease-app
  template:
    metadata:
      labels:
        app: shop-ease-app
    spec:
      containers:
      - name: shop-ease-app
        image: australia-southeast1-docker.pkg.dev/chrome-empire-452102-e5/shop-ease-repo/shop-ease-app:v1
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: connection-strings
              key: DefaultConnection
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"  # 0.5 CPU
            memory: "512Mi"  # 512 MB of memory
          limits:
            cpu: "1"  # 1 CPU
            memory: "1Gi"  # 1 GB of memory
---
apiVersion: v1
kind: Service
metadata:
  name: shop-ease-app-service
spec:
  selector:
    app: shop-ease-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
